### ISSUE TITLE
Add instructions to setup with AEM 6.5.12

### ISSUE THREAD

**Issue by keepthebyte** [duynguyen/aem-nextjs-template#3]
To make this example work with AEM 6.5.12 or newer - use these steps

To bootstrap the AEM project - use the archetype as follows:

```
mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=36\
 -D aemVersion=6.5.12 \
 -D appTitle="WKND App" \
 -D appId="wknd-app" \
 -D groupId="com.adobe.aem.guides.wkndapp" \
 -D frontendModule="react"
```

Install aem-guides-wknd.all-1.1.0-classic.zip from https://github.com/adobe/aem-guides-wknd/releases/tag/aem-guides-wknd-1.1.0 - the -classic.zip contains all dependencies needed to make the WKND site work on 6.5

The rest of the steps are the same (see readme in project root that is for Cloud Service).

**Comment by duynguyen** [comment]
added instruction to readme https://github.com/duynguyen/aem-nextjs-template#run-on-aem-65.
